google_cse.settings:
  type: mapping
  label: Settings
  mapping:
    custom_results_display:
      type: string
    results_prefix:
      type: string
    results_suffix:
      type: string
    cx:
      type: string
    safe:
      type: string
    results_display:
      type: string
    cof_here:
      type: string
    domain:
      type: string
    cof_google:
      type: string
    results_searchbox_width:
      type: integer
    adv_results_per_page:
      type: integer
    limit_domain:
      type: string
    results_display_images:
      type: boolean
    adv_language:
      type: string
    adv_maximum_results:
      type: integer
    results_tab:
      type: string
    results_width:
      type: integer
    sitesearch:
      type: string
    sitesearch_form:
      type: string
    sitesearch_option:
      type: string
    sitesearch_default:
      type: integer
    cr:
      type: string
    gl:
      type: string
    hl:
      type: string
    locale_hl:
      type: string
    ie:
      type: string
    lr:
      type: string
    locale_lr:
      type: string
    oe:
      type: string
    custom_css:
      type: string
    use_adv:
      type: integer
